### ISSUE TITLE
How to change the title of the pop-up page after clicking the download CV button

### ISSUE THREAD

**Issue by HgZnCH3** [GuangLun2000/GuangLun2000.github.io#17]
Hello Hanlin! When I click the download CV button on my website, I found that the title of the pop-up page is very weird (shown as Fig1, it's not my name). How should I change it? Thanks : )
<img width="172" alt="Fig1" src="https://github.com/GuangLun2000/GuangLun2000.github.io/assets/152170279/393c3f8e-e8d9-4f2a-b896-3cb682a57e5f">
<img width="183" alt="Fig2" src="https://github.com/GuangLun2000/GuangLun2000.github.io/assets/152170279/22492acd-a19d-4720-ab42-a17b547985cb">

**Comment by GuangLun2000** [comment]
This title is the original title of your .word source file. 
You can try to create a new .word file and name it as you want, then upload it to github repo.
Hope this can solve your problem ☺️
