### ISSUE TITLE
请问照片排版如何设置？

### ISSUE THREAD

**Issue by Yun-Tianming** [GuangLun2000/GuangLun2000.github.io#4]
大佬只给了三列排和居中排版的例子，css文件没有注释不太看得明白，想尝试更多的排版风格，例如双排、纵排、九宫格等等

**Comment by GuangLun2000** [comment]
图片的排版，是使用markdown文件中的内嵌html模块来实现

可以参考这个博客：https://blog.csdn.net/qq_33826564/article/details/81303230

有问题欢迎随时留言 😊

**Comment by Yun-Tianming** [comment]
谢谢！我再好好看看！

**Comment by GuangLun2000** [comment]
有问题随时留言

Feel free to leave a message if you have any questions
