### ISSUE TITLE
免费的评论系统

### ISSUE THREAD

**Issue by Yun-Tianming** [GuangLun2000/GuangLun2000.github.io#6]
大佬提供的评论系统是付费的，如果你想用免费的，可以参照我的再[折腾一下](https://blog.luofu.monster/blogs/%E4%B8%80%E4%B8%AA%E5%8D%9A%E5%AE%A2%E7%9A%84%E8%AF%9E%E7%94%9F)

**Comment by GuangLun2000** [comment]
原版的[Disqus评论系统](https://disqus.com/)也是免费的，不过需要登陆，会稍微麻烦一些

感谢你的建议！

**Comment by Yun-Tianming** [comment]
> 原版的[Disqus评论系统](https://disqus.com/)也是免费的，不过需要登陆，会稍微麻烦一些
> 
> 感谢你的建议！

抱歉是我没太搞明白，Waline全中文操作更有好一点，但体验下来disqus更流畅一些，Waline会加载更慢一些
