### ISSUE TITLE
请问如何让每一段不那么早换行？

### ISSUE THREAD

**Issue by Ma-Zijing** [GuangLun2000/GuangLun2000.github.io#7]
大佬您好，我想请问如何让每一段的文字不那么早换行。比如您的模板里面bio部分的文字换行的时候，右侧还有不少空白可以写，但是却换行了，这种应该怎么设置呢？谢谢！

**Comment by GuangLun2000** [comment]
很抱歉，现在才看到这个提问，您可以参考：https://github.com/Ephemeral182/Ephemeral182.github.io

适当修改CSS文件，可以达到您要的效果，修改前记得备份哦
