### ISSUE TITLE
关于微信内打开时页面乱码的问题

### ISSUE THREAD

**Issue by wangteamsysu** [GuangLun2000/GuangLun2000.github.io#8]
答主您好
      感谢您的分享，您在知乎的回答和视频我都有学习，再结合我们课题组的实际情况，fork了一个更简易的学术网站制作了主页，并且在阿里云购置了域名，然后对照您的帖子对内容进行了修改，不知道为什么我发现图片放入github中后，访问速度显著下降，在电脑中还勉强可以读取，移动端基本上图片直接卡死，所以我最后选择了图床储存，请问这是由于github的国内网络访问不稳定造成的吗？还有一个小问题，我发现同样的主页链接，有时候在不同的浏览器，尤其是微信中打开会出现排版错乱情况，有人说这是css文件异常，有人说是DNS解析异常，但更换设备打开有时候就正常了，这是跟设备相关吗？还是说在网页制作中也可以避免相关情况呢？

祝好
小K同学

**Comment by GuangLun2000** [comment]
我看了目前的主页，问题似乎已经解决了？

http://wangteamsysu.cn/

**Comment by GuangLun2000** [comment]
因为Github的访问DNS已经被污染（限制）了

所以国内源访问速度是很慢的，这个问题一般没法解决。除非把整个项目搬到阿里云等国内的源。

**Comment by GuangLun2000** [comment]
另外，你们课题组所使用的Academic Template网站模版，已经是非常成熟的项目了。

我个人认为，应该不存在设备的适配问题，还是因为网络访问限制，导致显示有误。

**Comment by GuangLun2000** [comment]
希望可以帮到你，有问题随时留言！
